apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: patient-management-service
  namespace: argocd

spec:

  project: default

  source:
    repoURL: https://github.com/Pradeep-216634/patient-management-gitops.git
    targetRevision: main
    path: patient-management-service

    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: patient-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true